server:
  port: 9095

spring:
  application:
    name: COMMENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost

spring.datasource.url: jdbc:mysql://localhost:3306/msf_commentservice?useSSL=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: 228244
spring.jpa.hibernate.ddl-auto: update