server:
  port: 9091

spring:
  application:
    name: FILE-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost

spring.datasource.url: jdbc:mysql://localhost:3306/msf_fileservice?useSSL=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: 228244
spring.jpa.hibernate.ddl-auto: update
spring.servlet.multipart.max-file-size: 150MB
spring.servlet.multipart.max-request-size: 150MB
spring.http.multipart.max-request-size: 150MB
spring.http.multipart.max-file-size: 150MB


